### ISSUE TITLE
图片url

### ISSUE THREAD

**Issue by Tiantian20000321** [TrustworthyComp/MCFEND_WWW#1]
作者您好，该数据集中的图片url在表中没有显示

**Comment by HarryHe11** [comment]
感谢关注我们的工作，谢谢您的提醒，我们会尽快检查数据问题，订正后会告知！

**Comment by HarryHe11** [comment]
您好，我们刚刚检查了我们公布的数据集，是无误的。并非所有news/social context都有图片。有些部分news/social context是纯文本的，对于这些条目，我们没有提供图片URL。如果您有特定需求，可以通过筛选功能获取所有包含图片的news/social context。感谢您对我们工作的关注，如果有新的问题，欢迎随时re-open此条issue!

**Comment by Tiantian20000321** [comment]
作者您好，图片链接http://ww1.sinaimg.cn/large/a1d3feabjw1e7i053vbhnj20c82a214x.jpgzheli是有什么特殊渠道打开吗，我这里打开显示403

**Comment by HarryHe11** [comment]
> 作者您好，图片链接[http://ww1.sinaimg.cn/large/a1d3feabjw1e7i053vbhnj20c82a214x.jpgzheli是有什么特殊渠道打开吗，我这里打开显示403](http://ww1.sinaimg.cn/large/a1d3feabjw1e7i053vbhnj20c82a214x.jpgzheli%E6%98%AF%E6%9C%89%E4%BB%80%E4%B9%88%E7%89%B9%E6%AE%8A%E6%B8%A0%E9%81%93%E6%89%93%E5%BC%80%E5%90%97%EF%BC%8C%E6%88%91%E8%BF%99%E9%87%8C%E6%89%93%E5%BC%80%E6%98%BE%E7%A4%BA403)

您好，这类url不能直接浏览器打开，可以参考下列代码
```
# 转换图片链接并下载图片
def download_image(url, save_path):
    response = requests.get(url)
    if response.status_code == 200:
        with open(save_path, 'wb') as f:
            f.write(response.content)
        print(f"下载成功: {url} -> {save_path}")
    else:
        print(f"下载失败: {url}")
```
